// src/components/Post/Categories.svelte
<script lang="ts">
  import { PostCategory } from '@c/Post'
  import { categoriesList } from '@/core/store/post'

  let activeCategoryId = null as number | null

  const handleToggle = (id: number) => {
    activeCategoryId = activeCategoryId === id ? null : id
  }
</script>

<div class="md:mx-auto md:max-w-md md:px-1">
  <h4 class="text-lg font-bold">Выберите категорию</h4>

  {#each $categoriesList as category}
    <PostCategory {category} {activeCategoryId} on:onToggle={(e) => handleToggle(e.detail)} />
  {/each}
</div>

// src/components/Post/Categories.vue
<template>
  <div class="md:mx-auto md:max-w-md md:px-1">
    <h4 class="text-lg font-bold">Выберите категорию</h4>

    <PostCategory
      v-for="category in categoriesList"
      :key="category.id"
      :category="category"
      :activeCategoryId="activeCategoryId"
      @on-toggle="handleToggle"
    />
  </div>
</template>

<script setup lang="ts">
import { PostCategory } from '@c/Post'

const postStore = usePostStore()
const { categoriesList } = storeToRefs(postStore)

const activeCategoryId = ref<number | null>(null)
const handleToggle = (id: number) => {
  activeCategoryId.value = activeCategoryId.value === id ? null : id
}

await postStore.getCategories()
</script>
