// src/components/Post/Location.vue
<template>
  <UiModal name="location" title="Добавить локацию">
    <div class="mt-4">
      <UiInput
        name="country"
        label="Страна"
        placeholder=""
        :value="country"
        :error="errors.country"
        :focusOnMount="true"
        @onChange="(v: string) => setFieldValue('country', v)"
      />
    </div>

    <div class="mt-4">
      <UiInput
        name="city"
        label="Город"
        placeholder=""
        :optional="true"
        :value="city"
        :error="errors.city"
        @onChange="(v: string) => setFieldValue('city', v)"
      />
    </div>

    <div class="mt-4">
      <UiInput
        name="address"
        label="Адрес"
        placeholder="Введите текст объявления"
        :optional="true"
        :value="address"
        :error="errors.address"
        @onChange="(v: string) => setFieldValue('address', v)"
      />
    </div>

    <div class="mt-4">
      <UiButton @click="save" block :loading="loading"> Продолжить </UiButton>
    </div>
  </UiModal>
</template>

<script setup lang="ts">
import { useToast } from 'vue-toast-notification'

const postStore = usePostStore()
const { order } = storeToRefs(postStore)
const ui = useUiStore()
const toast = useToast()

const { errors, setErrors, setFieldValue, validate } = useForm({
  initialValues: {
    country: order.value.location.country || '',
    city: order.value.location.city || '',
    address: order.value.location.address || '',
  },
})

const { value: country, meta: countryMeta } = useField('country', (v: any) => {
  return clearString(v) ? true : 'Текст обязателен для заполнения'
})

const { value: city, meta: cityMeta } = useField('city', (v: any) => {
  return true
})

const { value: address, meta: addressMeta } = useField('address', (v: any) => {
  if (!clearString(v)) return true
  return valid_adress(v) ? true : 'Укажите полный адрес, с номером дома и/или квартиры'
})

const loading = ref(false)

const save = async () => {
  const { valid, errors } = await validate()
  if (!valid) return

  loading.value = true
  postStore.updateOrder({
    location: {
      country: country.value,
      city: city.value,
      address: address.value,
    },
  })
  // await useApi('/save/', {
  //   method: 'POST',
  //   body: {
  //     country: country.value,
  //     city: city.value,
  //     address: address.value,
  //   },
  // }).catch((err) => {
  //   toast.error(err)
  // })

  loading.value = false

  ui.closeAllModals()
}
</script>

// src/components/Post/Location.svelte
<script lang="ts">
  import { form, field } from 'svelte-forms'
  import { toast } from '@zerodevx/svelte-toast'

  import { useApi } from '@/core/api'
  import { clearString, valid_adress } from '@/core/utils'
  import { updateOrder, order } from '@/core/store/post'
  import { closeAllModals } from '@/core/store/ui'
  import { UiModal, UiInput, UiButton } from '@c/Ui'

  // const { errors, setErrors, setFieldValue, validate } = useForm({
  //   initialValues: {
  //     country: $order.location.country || '',
  //     city: $order.location.city || '',
  //     address: $order.location.address || '',
  //   },
  // })

  const country = field('country', '', [
    (v) => {
      return {
        valid: !!clearString(v),
        name: 'Текст обязателен для заполнения',
      }
    },
  ])

  const city = field('city', '', [
    (v) => {
      return { valid: true, name: '' }
    },
  ])

  const address = field('address', '', [
    (v) => {
      if (!clearString(v)) return { valid: true, name: '' }
      return {
        valid: valid_adress(v),
        name: 'Укажите полный адрес, с номером дома и/или квартиры',
      }
    },
  ])

  const formInstance = form(country, city, address)

  let loading = false

  const save = async () => {
    const { valid, errors } = $formInstance
    if (!valid) return

    loading = true
    updateOrder({
      location: {
        country: $country.value,
        city: $city.value,
        address: $address.value,
      },
    })
    // await useApi('/save/', {
    //   method: 'POST',
    //   body: {
    //     country: country,
    //     city: city,
    //     address: address,
    //   },
    // }).catch((err) => {
    //   toast.push(err)
    // })

    loading = false

    closeAllModals()
  }
</script>

<UiModal name="location" title="Добавить локацию">
  <div class="mt-4">
    <UiInput
      name="country"
      label={'Страна'}
      placeholder=""
      value={$country.value}
      error={$country.errors[0]}
      focusOnMount={true}
      on:onChange={(v) => ($country.value = v.detail)}
    />
  </div>

  <div class="mt-4">
    <UiInput
      name="city"
      label={'Город'}
      placeholder=""
      optional={true}
      value={$city.value}
      error={$city.errors[0]}
      on:onChange={(v) => ($city.value = v.detail)}
    />
  </div>

  <div class="mt-4">
    <UiInput
      name="address"
      label={'Адрес'}
      placeholder="Введите текст объявления"
      optional={true}
      value={$address.value}
      error={$address.errors[0]}
      on:onChange={(v) => ($address.value = v.detail)}
    />
  </div>

  <div class="mt-4">
    <UiButton on:click={save} block :loading="loading">Продолжить</UiButton>
  </div>
</UiModal>
